# -*- coding: utf-8 -*-
"""Adult Income Prediction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVC_vPJIdG-SXbWrcv1esqtwoapIPYad
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as p
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('adult_income_prediction.csv')

print("Shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nFirst 5 rows:")
df.head()

df.describe()

df.info()

"""## Data Cleaning & Preprocessing"""

# Identifying missing values
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)  # Removes whitespace in all columns
missing_val = (df == '?').sum()
df.replace('?', np.nan, inplace=True)

print("Missing values in data :")
print(missing_val[missing_val > 0])

"""Without knowing the occupation, it defeats the purpose of the individual's career decision-making. Therefore, will be dropping the row with null occupation values."""

# Drop rows where 'occupation' is empty
df = df.dropna(subset=['occupation'])

missing_val = df.isnull().sum()

print("Missing values in data :")
print(missing_val[missing_val > 0])

# Identifying numerical columns and categorical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

print("Numerical Columns:\n", numerical_cols)
print("\nCategorical Columns:\n", categorical_cols)

# Show unique values in categorical columns
for column in df:
  print(f"Unique values in '{column}':\n{df[column].unique()}\n")

# Age column
df['age_group'] = pd.cut(df['age'], bins = range(30, 100, 10), right=False)
age_counts = df['age_group'].value_counts().sort_index()

# Capital Gain column
df['capitalGain_group'] = pd.cut(df['capital-gain'], bins = range(0, 100000, 10000), right=False)
capitalgain_counts = df['capitalGain_group'].value_counts().sort_index()

# Capital Loss column
df['capitalLoss_group'] = pd.cut(df['capital-loss'], bins = range(0, 5000, 1000), right=False)
capitalLoss_counts = df['capitalLoss_group'].value_counts().sort_index()

# Hours per week column
df['hrs_group'] = pd.cut(df['hours-per-week'], bins = range(0, 100, 10), right=False)
hrs_counts = df['hrs_group'].value_counts().sort_index()

# Education column Mapping
edu_mapping = {
    'Preschool': '1',
    '1st-4th': '2',
    '5th-6th': '3',
    '7th-8th': '4',
    '9th': '5',
    '10th': '6',
    '11th': '7',
    '12th': '8',
    'HS-grad': '9',
    'Some-college': '10',
    'Assoc-voc':  '11',
    'Assoc-acdm': '12',
    'Bachelors': '13',
    'Masters': '14',
    'Prof-school': '15',
    'Doctorate': '16',
}
df['education'] = df['education'].replace(edu_mapping)
df = df.drop(['education-num'], axis=1)

# Country column mapping
country_mapping = {
    'United-States': 'North America', 'Mexico': 'North America',
    'Canada': 'North America',

    'Cuba': 'LAC', 'Jamaica': 'LAC', 'Puerto-Rico': 'LAC', 'Columbia': 'LAC',
    'Ecuador': 'LAC', 'Haiti': 'LAC', 'Dominican-Republic': 'LAC', 'El-Salvador': 'LAC',
    'Guatemala': 'LAC', 'Peru': 'LAC', 'Trinadad&Tobago': 'LAC', 'Nicaragua': 'LAC',
    'Honduras': 'LAC',

    'India': 'Southern Asia',  'Iran': 'Southern Asia',
    'Taiwan': 'Eastern Asia', 'China': 'Eastern Asia', 'Japan': 'Eastern Asia', 'Hong': 'Eastern Asia',

    'Philippines': 'Southeast Asia', 'Cambodia': 'Southeast Asia',
    'Thailand': 'Southeast Asia', 'Laos': 'Southeast Asia', 'Vietnam': 'Southeast Asia',

    'England': 'Northern Europe', 'Scotland': 'Northern Europe', 'Ireland': 'Northern Europe',
    'Germany': 'Western Europe', 'France': 'Western Europe', 'Holand-Netherlands': 'Western Europe',
    'Poland': 'Eastern Europe', 'Hungary': 'Eastern Europe',

    'Portugal': 'Southern Europe', 'Italy': 'Southern Europe', 'Greece': 'Southern Europe',

    'Yugoslavia': 'Other', 'South': 'Other', 'Outlying-US(Guam-USVI-etc)': 'Other'
}
df['country'] = df['country'].replace(country_mapping)
df['country'] = df['country'].replace('Other', np.nan)

df1 = df.copy()
df1 = df1.drop(['age','capital-gain', 'capital-loss', 'hours-per-week'], axis=1)
for column in df1:
  print(f"Unique values in '{column}':\n{df1[column].unique()}\n")

# Export clean data
df1.to_csv("adultIncome_data_clean.csv", index=False)